name: threads
description: "test"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  image_picker: ^1.1.2
  video_player: ^2.9.5
  record: ^6.0.0
  just_audio: ^0.10.2
  path_provider: ^2.1.5
  just_waveform: ^0.0.7
  audio_waveforms: ^1.3.0
  image_cropper: ^9.1.0
  video_editor: ^3.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
   - assets/fonts/
   - assets/images/
   - assets/audio/
  #  - assets/lang/
fonts:
  - family: Shabnam
    fonts:
      - asset: fonts/Shabnam.ttf
  #   - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700